sudo: false

language: java
jdk:
  - oraclejdk10

git:
  depth: 1

env:
  global:
    - GH_REPO_NAME: islands
    - DOC_BUILD_DIR: docs

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $GOCACHE
    - $GOPATH

before_install:
  - eval "$(gimme 1.10)"
  - go version && go env

install:
  - .scripts/install-spigot.sh 1.12.2

script:
  - ./gradlew clean --stacktrace
  - ./gradlew test check --stacktrace
  - ./gradlew fatjar --stacktrace
  - ./gradlew javadoc --stacktrace

deploy:
  - provider: script
    script: ./gradlew core:artifactoryPublish --stacktrace
    on:
      branch:
        - master
        - develop
  # Deploy to netlify
  - provider: script
    script: .scripts/netlifyctl.sh
    on:
      branch: master

notifications:
  email:
    on_success: never