# Use new container infrastructure to enable caching
sudo: false

# Specify language
language: java
jdk:
  - oraclejdk8

# Caching so the next build will be fast too.
cache:
  directories:
    - $HOME/.m2

# Only re-download spigot if we don't have spigot in the repo
before_install:
  - if [ ! -d "$HOME/.m2/repository/org/spigotmc" ]; then ./installSpigot.sh 1.12.2 ; else echo "Not compiling Spigot because it is already in our maven" ; fi

# Gradlew clean and build a fatJar
install:
  - ./gradlew core:clean core:fatjar core:artifactoryPublish --stacktrace
  - ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD
  - ./jfrog rt u "core/build/libs/*.jar" islandswars --build-name=travisci-generic-artifactory --build-number=$TRAVIS_BUILD_NUMBER --flat=false
  - ./jfrog rt bce travisci-generic-artifactory $TRAVIS_BUILD_NUMBER
  - ./jfrog rt bp travisci-generic-artifactory $TRAVIS_BUILD_NUMBER
